# Generated by Django 4.0.3 on 2023-02-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_text', models.TextField()),
                ('comment_time', models.DateTimeField()),
                ('parent_comment_id', models.IntegerField()),
            ],
            options={
                'db_table': 'comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dislikes',
            fields=[
                ('dislike_id', models.AutoField(primary_key=True, serialize=False)),
                ('dislike_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'dislikes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('like_id', models.AutoField(primary_key=True, serialize=False)),
                ('like_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'likes',
                'managed': False,
            },
        ),
    ]
