# Generated by Django 4.0.3 on 2023-02-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('parent_id', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Playlists',
            fields=[
                ('playlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('playlist_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'playlists',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Videoanalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_time', models.TimeField(blank=True, null=True)),
                ('ctr', models.FloatField(blank=True, null=True)),
                ('avg_view_length', models.TimeField(blank=True, null=True)),
                ('drop_off_rate', models.FloatField(blank=True, null=True)),
                ('audience_retention', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'videoanalytics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Videodetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail', models.CharField(blank=True, max_length=255, null=True)),
                ('video_file', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('views', models.IntegerField(blank=True, null=True)),
                ('likes', models.IntegerField(blank=True, null=True)),
                ('fun_tokens', models.IntegerField(blank=True, null=True)),
                ('value_tokens', models.IntegerField(blank=True, null=True)),
                ('comments', models.IntegerField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('upload_date', models.DateTimeField(blank=True, null=True)),
                ('privacy', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'videodetails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Viewerinformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo_location', models.CharField(blank=True, max_length=255, null=True)),
                ('device', models.CharField(blank=True, max_length=255, null=True)),
                ('referrer', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'viewerinformation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Views',
            fields=[
                ('view_id', models.AutoField(primary_key=True, serialize=False)),
                ('view_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'views',
                'managed': False,
            },
        ),
    ]
